groups:
- name: CulinaryCanvas
  rules:
  - alert: HighErrorRate
    expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "High HTTP 5xx error rate"
      description: "More than 5% of requests are resulting in 5xx errors for the past 1 minute"

  - alert: APILatencyHigh
    expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler="/api/recipes"}[5m])) by (le)) > 2
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "API Latency too high"
      description: "95th percentile of request duration is above 2 seconds for /api/recipes endpoint"

  - alert: HighCPUUsage
    expr: avg(rate(node_cpu_seconds_total{mode!="idle"}[5m])) by (instance) > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for 5 minutes on {{ $labels.instance }}"

  - alert: MemoryUsageHigh
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "More than 90% of memory is used on {{ $labels.instance }}"

  - alert: DiskSpaceLow
    expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Low disk space"
      description: "Less than 10% disk space available on {{ $labels.instance }}"

  - alert: TooManyRequests
    expr: sum(rate(http_requests_total[1m])) > 100
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High request rate"
      description: "More than 100 requests per second for 2 minutes"

  - alert: SlowDatabaseQueries
    expr: histogram_quantile(0.95, sum(rate(database_query_duration_seconds_bucket[5m])) by (le, query_type)) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Slow database queries"
      description: "95th percentile of {{ $labels.query_type }} database queries is taking more than 1 second"

  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} has been down for more than 1 minute"

  - alert: BackendErrorRate
    expr: sum(rate(supabase_error_total[5m])) / sum(rate(supabase_requests_total[5m])) > 0.05
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High Supabase error rate"
      description: "More than 5% of Supabase requests are resulting in errors"

  - alert: JWTValidationErrors
    expr: sum(rate(auth_jwt_validation_errors_total[5m])) > 5
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High rate of JWT validation errors"
      description: "More than 5 JWT validation errors per second for 2 minutes" 