name: SonarCloud Analysis

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  # Run on a schedule for regular analysis
  schedule:
    - cron: '0 8 * * 1'  # Run every Monday at 8:00 AM UTC
  # Allow manual trigger
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better SonarCloud analysis
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests with coverage
        run: npm test -- --coverage
        continue-on-error: true  # Don't fail if tests fail
        
      - name: Verify sonar-project.properties
        run: |
          echo "Current directory: $(pwd)"
          echo "sonar-project.properties content:"
          cat sonar-project.properties
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: ${{ runner.os }}-sonar
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Generate a token on SonarCloud.io, add to repository's secrets
        
      - name: SonarCloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Wait for Quality Gate analysis and fail based on Quality Gate results
        timeout-minutes: 5
        continue-on-error: true  # Don't fail the workflow if Quality Gate fails 